name = "hello-friend-ng-mod"
license = "MIT"
licenselink = "https://github.com/abhishekarya1/hello-friend-ng-mod/blob/master/LICENSE.md"
description = "A custom mod of hello-friend-ng theme by rhazdan"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Abhishek Arya"
  homepage = "https://abhishekarya.com"

[original]
  name = "hello-friend"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
